export const adminText = {
  shell: {
    eyebrow: "Scoreboard Admin",
    title: "Beheer Pagina",
  },
  inputShell: {
    eyebrow: "Scoreboard invoerscherm",
    title: "Voer Laptime in",
    intro: "",
  },
  page: {
    openPublicScoreboard: "Open Scoreboard",
    openAdminPage: "Open Invoerscherm",
    openAdminDashboard: "Open Admin Dashboard",
    newLapTitle: "Nieuwe tijd invoeren",
    newLapIntro: "",
    recentTimesTitle: "Recente tijden"
  },
  lapForm: {
    driverLabel: "Coureur",
    driverPlaceholder: "Kies een Coureur",
    emptyDrivers: "Nog geen coureurs beschikbaar.",
    circuitLabel: "Circuit",
    circuitPlaceholder: "Kies een circuit",
    lapTimeLabel: "Lap time",
    lapTimePlaceholder: "Tik cijfers, bv. 123456",
    setupLabel: "Setup",
    setupPlaceholder: "Kies een setup",
    isWetLabel: "Weer",
    createDriver: "Creëer een Coureur",
    newDriverPlaceholder: "Naam Coureur",
    saveDriver: "Opslaan",
    cancelDriver: "Annuleer",
    addDriverEmptyError: "Vul eerst een Coureur in.",
    addDriverError: "Coureur aanmaken mislukt.",
    addDriverSuccess: 'Coureur "{name}" toegevoegd.',
    confirmDeleteDriver: 'Weet je zeker dat je "{name}" en al zijn tijden wilt verwijderen?',
    deleteDriver: "Verwijder Coureur",
    deleteDriverAria: 'Verwijder Coureur "{name}" en al zijn tijden',
    deleteDriverError: "Coureur verwijderen mislukt.",
    deleteDriverSuccess: 'Coureur "{name}" verwijderd.',
    saveError: "Opslaan mislukt.",
    saveSkipped: "Niet opgeslagen.",
    saveSuccess: "Rondetijd opgeslagen.",
    recordSuccess: "Nieuwe snelste tijd op dit circuit!",
    submitting: "Opslaan...",
    submit: "Tijd opslaan",
    seatLabel: "Stoel selectie"
  },
  trackList: {
    allCircuits: "Alle circuits",
    filterLabel: "Circuit:",
    fastestLapLabel: "Snelste ronde",
    emptyMessage: "Nog geen tijden beschikbaar voor dit circuit."
  },
  recentTimesList: {
    confirmDelete: "Weet je zeker dat je deze tijd wilt verwijderen?",
    deleteError: "Verwijderen mislukt.",
    deleteSuccess: "Tijd verwijderd.",
    emptyMessage: "Nog geen tijden beschikbaar.",
    deleting: "Bezig...",
    delete: "Verwijder"
  },
  auth: {
    loginTitle: "Admin login",
    loginIntro: "Log in met de standaardgegevens `admin` / `admin`. Na de eerste login moet het wachtwoord direct gewijzigd worden.",
    usernameLabel: "Gebruikersnaam",
    usernamePlaceholder: "admin",
    passwordLabel: "Wachtwoord",
    passwordPlaceholder: "Voer wachtwoord in",
    loginButton: "Inloggen",
    loggingIn: "Bezig...",
    loginError: "Inloggen mislukt.",
    loggedOutMessage: "Je bent uitgelogd.",
    missingCredentials: "Vul gebruikersnaam en wachtwoord in.",
    invalidCredentials: "Onjuiste gebruikersnaam of wachtwoord.",
    notAuthenticated: "Niet ingelogd.",
    passwordChangeRequired: "Wijzig eerst het standaard wachtwoord.",
    firstLoginTitle: "Wijzig eerst het standaard wachtwoord",
    firstLoginIntro: "Je bent ingelogd met het standaard account. Kies nu eerst een nieuw wachtwoord voordat je verdergaat.",
    changePasswordTitle: "Wachtwoord wijzigen",
    changePasswordIntro: "Werk hier het admin-wachtwoord bij.",
    currentPasswordLabel: "Huidig wachtwoord",
    currentPasswordPlaceholder: "Huidig wachtwoord",
    newPasswordLabel: "Nieuw wachtwoord",
    newPasswordPlaceholder: "Kies een nieuw wachtwoord",
    confirmPasswordLabel: "Bevestig nieuw wachtwoord",
    confirmPasswordPlaceholder: "Voer het nieuwe wachtwoord opnieuw in",
    savePasswordButton: "Wachtwoord opslaan",
    savingPassword: "Opslaan...",
    passwordMismatch: "De nieuwe wachtwoorden komen niet overeen.",
    passwordChangeError: "Wachtwoord wijzigen mislukt.",
    passwordFieldsRequired: "Vul het huidige en nieuwe wachtwoord in.",
    passwordTooShort: "Kies een wachtwoord van minimaal 4 tekens.",
    currentPasswordInvalid: "Het huidige wachtwoord klopt niet.",
    passwordMustChangeFromDefault: "Kies een ander wachtwoord dan het standaard wachtwoord."
  },
  adminPage: {
    totalRecordsLabel: "Totaal records",
    totalDriversLabel: "Coureurs",
    totalTracksLabel: "Circuits",
    lastUpdateLabel: "Laatste update",
    databaseTitle: "Database overzicht",
    roadmapTitle: "Voorbereid op later",
    roadmapIntro: "Deze sectie laat alvast zien waar import, export en version control logisch kunnen landen.",
    exportCardTitle: "Export",
    exportCardBody: "De CSV-export is direct beschikbaar vanuit deze beheerpagina, zodat je snel een back-up kunt maken.",
    importCardTitle: "Import",
    importCardBody: "Hier kunnen we later een upload-flow toevoegen voor CSV- of database-imports met validatie en preview.",
    versionControlCardTitle: "Version control",
    versionControlCardBody: "Hier kunnen we later snapshots, changelogs of koppelingen naar git/deploy-history tonen.",
    footerCopyright: "© F1 Scoreboard",
    footerVersion: "Versie {version}"
  },
  database: {
    searchLabel: "Zoeken",
    searchPlaceholder: "Zoek op coureur, circuit, setup of stoel",
    trackFilterLabel: "Filter op circuit",
    allTracks: "Alle circuits",
    openInputPage: "Open Invoerscherm",
    exportNow: "Exporteer CSV",
    resultsLabel: "{count} records zichtbaar",
    emptyMessage: "Geen records gevonden voor deze filters.",
    confirmDelete: "Weet je zeker dat je dit record wilt verwijderen?",
    editDriver: "Wijzig naam",
    saveDriver: "Opslaan",
    cancelEdit: "Annuleer",
    renameDriverPlaceholder: "Nieuwe coureurnaam",
    renameDriverPrompt: "Voer de nieuwe coureurnaam in",
    deleteError: "Verwijderen mislukt.",
    deleteSuccess: "Record verwijderd.",
    deleting: "Bezig...",
    saving: "Opslaan...",
    delete: "Verwijder",
    driverLabel: "Coureur",
    idLabel: "ID",
    lapTimeLabel: "Tijd",
    trackLabel: "Circuit",
    setupLabel: "Setup",
    seatLabel: "Stoel",
    sessionDateLabel: "Sessie datum",
    createdAtLabel: "Aangemaakt op",
    actionsLabel: "Acties"
  },
  import: {
    title: "Import CSV",
    intro: "Importeer een CSV-bestand om records terug te zetten in de database.",
    fileLabel: "CSV-bestand",
    replaceExisting: "Verwijder alle records",
    hint: "Vink aan om te importeren op een lege database. Let op, alle bestaande records zullen worden gewist.",
    submit: "Importeer CSV",
    importing: "Importeren...",
    fileRequired: "Kies eerst een CSV-bestand.",
    invalidFile: "Het CSV-bestand lijkt leeg of onvolledig.",
    invalidHeaders: "Dit CSV-bestand heeft niet het verwachte exportformaat.",
    invalidRow: "Rij {row} bevat ongeldige of ontbrekende data.",
    success: "{count} records en {drivers} coureurs geimporteerd.",
    successFallback: "Import voltooid.",
    serverError: "Importeren mislukt door een server- of databasefout."
  },
  notes: {
    title: "Nog toevoegen:",
    body: "Bewerken van records, change log, Actieve Circuits"
  },
  api: {
    driverRequired: "Vul een Coureur in.",
    driverInvalidId: "Ongeldige Coureur-id.",
    driverNotFound: "Coureur niet gevonden.",
    driverCreateServerError: "Coureur aanmaken mislukt door een server- of databasefout.",
    driverDeleteServerError: "Coureur verwijderen mislukt door een server- of databasefout.",
    driverDeleted: "Coureur en tijden verwijderd.",
    driverRenamed: "Coureurnaam gewijzigd.",
    driverRenameNoChange: "De coureurnaam is niet gewijzigd.",
    driverNameAlreadyExists: "Er bestaat al een coureur met die naam.",
    lapTimeInvalidId: "Ongeldig record-id.",
    lapTimeNotFound: "Tijd niet gevonden.",
    lapTimeMissingFields: "Vul Coureur, circuit, lap time en stoel in.",
    lapTimeFormatError: "Gebruik een tijd zoals 1:23.456 of 83.456.",
    lapTimeRangeError: "Gebruik een rondetijd tussen 30 seconden en 2 minuten.",
    lapTimeSkipped: "Niet opgeslagen: deze Coureur heeft op dit circuit al een snellere of gelijke tijd.",
    lapTimeReplaced: "Snellere tijd opgeslagen. De vorige tijd van deze Coureur op dit circuit is vervangen.",
    lapTimeSaved: "Rondetijd opgeslagen.",
    lapTimeRecord: "Nieuwe snelste tijd op dit circuit!",
    lapTimeDeleteServerError: "Verwijderen mislukt door een server- of databasefout.",
    lapTimeServerError: "Opslaan mislukt door een server- of databasefout.",
    driverRenameServerError: "Coureur hernoemen mislukt door een server- of databasefout."
  }
};
